language: node_js
os: linux
dist: bionic

matrix:
  include:
    - name: Run tests and coverage on stable Node.js
      node_js: stable
      script: npm run cov
      after_script: |
        npm i -g coveralls
        ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls
    - name: Run tests on Node.js 12
      node_js: 12
      script: npm run test:mocha
    - name: Run tests on Node.js 10
      node_js: 10
      script: npm run test:mocha
    - name: Run linting checks
      node_js: lts/*
      script: npm run test:lint
