language: node_js
sudo: false
node_js:
  - stable
  - 8
  - 7
  - 6

before_install:
  - nvm install-latest-npm
after_script:
  - 'if [[ x$TRAVIS_NODE_VERSION == xstable ]]; then npm i -g coveralls; ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls; fi'
