name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
      - name: Check code style
        run: npm run lint
  test:
    name: Tests
    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run tests-only
      - name: Submit coverage
        if: matrix.node-version == '16.x'
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
